server:
  port: 8080
  servlet:
    context-path: /shopping
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        max-age: 36000
        allowed-headers: '*'
        exposed-headers: "X-Get-Header"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: shopping
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: test


jwt:
  secret: hl